# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    identifier: 60b7c4e8
    url: /
    weight: 10
  - name: Projects
    identifier: 814598ee
    url: /projects
    weight: 20
  - name: Topics
    identifier: "539801e0"
    url: tags/
    weight: 30
  - name: Contact
    identifier: c3d90fa7
    url: /contact
    weight: 40
