# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

remote_theme: "mmistakes/minimal-mistakes@4.22.0"
minimal_mistakes_skin    : "default" # "air", "contrast", "dark", "dirt", "mint", "sunrise"

# Site Settings
locale                   : "en"
title                    : "Meher Béjaoui's Blog" #Site Title
title_separator          : "-"
subtitle                 : # site tagline that appears below site title in masthead
name                     : "Meher Béjaoui" #Your Name
description              : "Personal and educational blog about Python language, pandas library, matplotlib and other scientific libraries - by Meher Béjaoui."
url                      : "https://meherbejaoui.com" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : "meherbejaoui/meherbejaoui.github.io" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser                   : /assets/images/site-logo.jpg # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200
comments:
  provider               : "disqus" # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "staticman_v2" "custom"
  disqus:
    shortname            : "meherbejaoui" # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
reCaptcha:
  siteKey                :
  secret                 :
atom_feed:
  path                   : # blank (default) uses feed.xml
  hide                   : # true, false (default)
search: false
search_full_content      : # true, false (default)
search_provider          : google # lunr (default), algolia, google
google:
  search_engine_id       : 012662682197289494790:6dok1xjk-8k # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true

# SEO Related
google_site_verification :
bing_site_verification   : "6746FB8FF682FBA0CDA0A5AE1833ECBD"
alexa_site_verification  :
yandex_site_verification :
naver-site-verification  :

# Social Sharing
twitter:
  username               : "meher_bejaoui"
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : /assets/images/site-logo.jpg # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
    - "https://twitter.com/meher_bejaoui"
    - "https://www.linkedin.com/in/meherbejaoui/en"

# Analytics
analytics:
  provider               : "google-universal" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "UA-110152742-1"

# Site Author
author:
  name             : "Meher Béjaoui"
  avatar           : "/assets/images/myAvatar.jpg" # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "Engineer - Data science & visualizations"
  location         : "Tunisia"
  email            : "meher.bejaoui@outlook.com"
  links            :
    - label: "linkedin"
      icon: "fab fa-fw fa-linkedin"
      url:  "https://www.linkedin.com/in/meherbejaoui"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/meher_bejaoui"
    - label: "stackoverflow"
      icon: "fab fa-fw fa-stack-overflow"
      url: "https://stackoverflow.com/users/6452770/meher-b%c3%a9jaoui"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/meherbejaoui"

# Site Footer
footer:
  links:
    - label: "linkedin"
      icon: "fab fa-fw fa-linkedin"
      url:  "https://www.linkedin.com/in/meherbejaoui"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/meher_bejaoui"
    - label: "stackoverflow"
      icon: "fab fa-fw fa-stack-overflow"
      url: "https://stackoverflow.com/users/6452770/meher-b%c3%a9jaoui"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/meherbejaoui"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Africa/Tunis # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      show_date: true
      comments:  true
      share: true
      related: false
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
